
package com.cdyne.ws;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DelayedStockQuoteSoap", targetNamespace = "http://ws.cdyne.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DelayedStockQuoteSoap {


    /**
     * This method retrieves a current stock quote.  Use a license key of 0 for testing.
     * 
     * @param licenseKey
     * @param stockSymbol
     * @return
     *     returns com.cdyne.ws.QuoteData
     */
    @WebMethod(operationName = "GetQuote", action = "http://ws.cdyne.com/GetQuote")
    @WebResult(name = "GetQuoteResult", targetNamespace = "http://ws.cdyne.com/")
    @RequestWrapper(localName = "GetQuote", targetNamespace = "http://ws.cdyne.com/", className = "com.cdyne.ws.GetQuote")
    @ResponseWrapper(localName = "GetQuoteResponse", targetNamespace = "http://ws.cdyne.com/", className = "com.cdyne.ws.GetQuoteResponse")
    public QuoteData getQuote(
        @WebParam(name = "StockSymbol", targetNamespace = "http://ws.cdyne.com/")
        String stockSymbol,
        @WebParam(name = "LicenseKey", targetNamespace = "http://ws.cdyne.com/")
        String licenseKey);

    /**
     * This method retrieves just a stock price.  Use a license key of 0 for testing.
     * 
     * @param licenseKey
     * @param stockSymbol
     * @return
     *     returns java.math.BigDecimal
     */
    @WebMethod(operationName = "GetQuickQuote", action = "http://ws.cdyne.com/GetQuickQuote")
    @WebResult(name = "GetQuickQuoteResult", targetNamespace = "http://ws.cdyne.com/")
    @RequestWrapper(localName = "GetQuickQuote", targetNamespace = "http://ws.cdyne.com/", className = "com.cdyne.ws.GetQuickQuote")
    @ResponseWrapper(localName = "GetQuickQuoteResponse", targetNamespace = "http://ws.cdyne.com/", className = "com.cdyne.ws.GetQuickQuoteResponse")
    public BigDecimal getQuickQuote(
        @WebParam(name = "StockSymbol", targetNamespace = "http://ws.cdyne.com/")
        String stockSymbol,
        @WebParam(name = "LicenseKey", targetNamespace = "http://ws.cdyne.com/")
        String licenseKey);

    /**
     * This method retrieves the stock information and returns it in a dataset.  Use a , to diplay multiple quotes.  Use a license key of 0 for testing.
     * 
     * @param licenseKey
     * @param stockSymbols
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "GetQuoteDataSet", action = "http://ws.cdyne.com/GetQuoteDataSet")
    @WebResult(name = "GetQuoteDataSetResult", targetNamespace = "http://ws.cdyne.com/")
    @RequestWrapper(localName = "GetQuoteDataSet", targetNamespace = "http://ws.cdyne.com/", className = "com.cdyne.ws.GetQuoteDataSet")
    @ResponseWrapper(localName = "GetQuoteDataSetResponse", targetNamespace = "http://ws.cdyne.com/", className = "com.cdyne.ws.GetQuoteDataSetResponse")
    public Object getQuoteDataSet(
        @WebParam(name = "StockSymbols", targetNamespace = "http://ws.cdyne.com/")
        String stockSymbols,
        @WebParam(name = "LicenseKey", targetNamespace = "http://ws.cdyne.com/")
        String licenseKey);

}
